[workspace]
members = [
    "hello_world",
    "guessing_game",
    "postgres_console_app",
    "learning_rust",
    "learning_rust_tests",
    "level1_task1_temperature",
    "level1_task2_circle_area",
    "level1_task3_sum_of_squares",
    "level1_task4_is_prime",
    "level1_task5_array_processing",
    "level2_task6_count_vowels",
    "level2_task7_reverse_string",
    "level2_task8_first_word",
    "level2_task9_is_palindrome",
    "level2_task10_even_numbers",
]
resolver = "2"
